Repository semver4j/semver4j, pull requests merged in 2022-12, with the labels that each got.

#103 Move `RangesListFactory` from internal to root package
  src/main/java/org/semver4j/RangesListFactory.java
  src/main/java/org/semver4j/Semver.java
  src/test/java/org/semver4j/RangesListFactoryTest.java
Labels: enhancement

#104 Fix parsing IVY ranges with patch
  src/main/java/org/semver4j/internal/Tokenizers.java
  src/main/java/org/semver4j/internal/range/processor/IvyProcessor.java
  src/test/java/org/semver4j/internal/range/processor/IvyProcessorTest.java
Labels: bug

#105 Fix GitHub workflow
  .github/workflows/release.yml
Labels: bug, skip-changelog

#106 Update README.md
  README.md
Labels: documentation, skip-changelog

#108 Add `isSatisfiedByAny()` to `Range` and `RangesList`
  src/main/java/org/semver4j/Range.java
  src/main/java/org/semver4j/RangesList.java
  src/main/java/org/semver4j/Semver.java
  src/main/java/org/semver4j/internal/range/processor/GreaterThanOrEqualZeroProcessor.java
  src/test/java/org/semver4j/RangeTest.java
  src/test/java/org/semver4j/RangesListFactoryTest.java
Labels: enhancement

#110 Remove `SemverType` enum
  src/main/java/org/semver4j/Semver.java
Labels: breaking

#111 Update README.md
  README.md
Labels: documentation, skip-changelog

#113 Polishing of documentation
  src/main/java/org/semver4j/RangesList.java
Labels: documentation

#114 Polishing of documentation
  src/main/java/org/semver4j/RangesList.java
Labels: documentation, skip-changelog

#116 Strip whitespaces between range operator
  src/main/java/org/semver4j/RangesListFactory.java
  src/test/java/org/semver4j/RangesListFactoryTest.java
Labels: enhancement

#117 Polish RangesList
  src/main/java/org/semver4j/RangesList.java
Labels: refactor, skip-changelog

#122 Fix parsing caret ranges (cleanup trailing space)
  src/main/java/org/semver4j/RangesListFactory.java
  src/test/java/org/semver4j/RangesListFactoryTest.java
  src/test/java/org/semver4j/internal/range/processor/CaretProcessorTest.java
Labels: bug

#123 Update versions after v4.1.1 release
  README.md
Labels: documentation, skip-changelog
