Repository semver4j/semver4j, pull requests merged in 2022-09, with the labels that each got.

#74 feat: SEM-48 add validation to protect int overflow
  src/main/java/org/semver4j/internal/StrictParser.java
  src/test/java/org/semver4j/internal/StrictParserTest.java
Labels: enhancement

#78 Update README.md
  README.md
Labels: skip-changelog

#80 Add mvn wrapper and use it in GitHub Actions
  .github/workflows/ci.yml
  .github/workflows/release.yml
  .mvn/wrapper/maven-wrapper.jar
  .mvn/wrapper/maven-wrapper.properties
  mvnw
  mvnw.cmd
Labels: refactor

#82 Add support for .editorconfig
  .editorconfig
  README.md
  src/main/java/org/semver4j/internal/StrictParser.java
Labels: refactor

#84 83 add checkstyle plugin
  .github/workflows/ci.yml
  config/checkstyle/checkstyle.xml
  pom.xml
  src/main/java/org/semver4j/Range.java
  src/main/java/org/semver4j/RangesList.java
  src/main/java/org/semver4j/internal/Modifier.java
  src/main/java/org/semver4j/internal/StrictParser.java
  src/main/java/org/semver4j/internal/Tokenizers.java
  src/main/java/org/semver4j/internal/range/RangesListFactory.java
  src/test/java/org/semver4j/SemverTest.java
Labels: refactor
