Repository semver4j/semver4j, pull requests merged in 2024-04, with the labels that each got.

#230 Using longs to parse identifiers instead of ints to avoid issues when parsing timestamp-sized values
  src/main/java/org/semver4j/internal/Comparator.java
  src/test/java/org/semver4j/SemverTest.java
Labels: bug

#232 Cleanup unnecessary Javadoc
  .github/release-drafter.yml
  src/main/java/org/semver4j/Semver.java
Labels: housekeeping

#233 Introduce a `Semver.Builder`
  .editorconfig
  README.md
  src/main/java/org/semver4j/Semver.java
  src/test/java/org/semver4j/SemverTest.java
Labels: enhancement

#238 Fixing trailing non-numerical character parsing issue
  src/main/java/org/semver4j/internal/Comparator.java
  src/test/java/org/semver4j/SemverTest.java
Labels: bug

#242 Introduce a Semver.of method for basic creation
  src/main/java/org/semver4j/Semver.java
  src/test/java/org/semver4j/SemverTest.java
Labels: enhancement

#244 Prerelease check improvements
  src/main/java/org/semver4j/internal/Comparator.java
  src/test/java/org/semver4j/SemverTest.java
Labels: bug

#240 Conversion of internal package classes to use static only
  src/main/java/org/semver4j/Semver.java
  src/main/java/org/semver4j/internal/Coerce.java
  src/main/java/org/semver4j/internal/Comparator.java
  src/main/java/org/semver4j/internal/Differ.java
  src/main/java/org/semver4j/internal/Modifier.java
  src/main/java/org/semver4j/internal/StrictParser.java
  src/main/java/org/semver4j/internal/Tokenizers.java
  src/test/java/org/semver4j/internal/StrictParserTest.java
Labels: refactor

#248 Fixing a merge failure from previous PRs
  src/main/java/org/semver4j/internal/Comparator.java
Labels: bug, skip-changelog

#252 Introduce formatter methods to customize version output
  README.md
  src/main/java/org/semver4j/Semver.java
  src/test/java/org/semver4j/SemverTest.java
Labels: enhancement

#255 Fix CI badge address
  README.md
Labels: skip-changelog, housekeeping
